"""migrate

Revision ID: 659cded16015
Revises: 
Create Date: 2023-05-21 12:52:42.329418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '659cded16015'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age2', sa.Integer(), nullable=False))
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.LargeBinary(),
               existing_nullable=True)
        batch_op.drop_column('age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.INTEGER(), nullable=False))
        batch_op.alter_column('photo',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('age2')

    # ### end Alembic commands ###
